contact_links:
  - name: Ask on Telegram
    url: https://t.me/ogen_dev
    about: Telegram group for ogen
  - name: Ask on GitHub
    url: https://github.com/ogen-go/ogen/discussions/new?category=q-a
    about: Q&A on GitHub
  - name: FAQ
    url: https://ogen.dev/docs/faq
    about: Troubleshooting
blank_issues_enabled: true
